name: hello-world
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "What can you say?"
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: say hello
      - run: make say-hello
